// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
//  nexus-cli — `nexus init <name>` command
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

import { Command } from 'commander';
import chalk from 'chalk';
import ora from 'ora';
import { mkdirSync, writeFileSync, existsSync } from 'node:fs';
import { resolve, join } from 'node:path';

// ── Scaffold templates ────────────────────────────

function makePackageJson(name: string): string {
  return JSON.stringify(
    {
      name,
      version: '0.1.0',
      type: 'module',
      scripts: {
        dev: 'npx tsx src/index.ts',
        build: 'npx tsup src/index.ts --format esm --dts',
      },
      dependencies: {
        'nexus-core': '*',
      },
      devDependencies: {
        typescript: '^6.0.0',
        '@types/node': '^22.0.0',
        tsup: '^9.0.0',
        tsx: '^4.0.0',
      },
    },
    null,
    2,
  );
}

function makeTsConfig(): string {
  return JSON.stringify(
    {
      compilerOptions: {
        target: 'ES2022',
        module: 'NodeNext',
        moduleResolution: 'NodeNext',
        lib: ['ES2022'],
        outDir: 'dist',
        rootDir: 'src',
        strict: true,
        esModuleInterop: true,
        skipLibCheck: true,
        forceConsistentCasingInFileNames: true,
        declaration: true,
        sourceMap: true,
        noUncheckedIndexedAccess: true,
      },
      include: ['src/**/*'],
      exclude: ['node_modules', 'dist'],
    },
    null,
    2,
  );
}

function makeIndexTs(name: string): string {
  return `// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
//  ${name} — Nexus agent team entry point
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
//
//  Generated by \`nexus init\`. Edit agent configs and
//  swap in your own prompts, tools, and protocols.
//
//  Run: ANTHROPIC_API_KEY=<key> npm run dev

import { Team } from 'nexus-core';
import type { TeamConfig, TeamRunInput } from 'nexus-core';

// ── Agent configuration ───────────────────────────

const teamConfig: TeamConfig = {
  protocol: 'sequential',
  rounds: 1,
  agents: [
    {
      id: 'analyst',
      name: 'Analyst',
      icon: '🔍',
      color: 'cyan',
      systemPrompt:
        'You are a concise analyst. Given a topic, produce a structured ' +
        '3-point breakdown covering key facts, risks, and opportunities. ' +
        'Keep your response under 150 words.',
    },
    {
      id: 'critic',
      name: 'Critic',
      icon: '🎯',
      color: 'yellow',
      systemPrompt:
        'You are a constructive critic. Review the Analyst\\'s breakdown and ' +
        'identify the single most important gap or assumption. ' +
        'Be specific and concise — under 100 words.',
    },
  ],
};

// ── Run ───────────────────────────────────────────

async function main(): Promise<void> {
  const topic = process.argv[2] ?? 'The future of AI agents in software development';

  console.log('\\n  Nexus Team: ' + teamConfig.agents.map((a) => a.name).join(' → '));
  console.log('  Topic: ' + topic + '\\n');

  const team = new Team(teamConfig);
  const input: TeamRunInput = { topic };

  const result = await team.run(input);

  for (const entry of result.transcript) {
    console.log(\`\\n[\${entry.agentName}]\`);
    console.log(entry.content);
  }

  console.log('\\n  Done in ' + result.totalLatencyMs + 'ms');
  console.log(
    '  Tokens: ' +
      result.totalTokens.inputTokens +
      ' in / ' +
      result.totalTokens.outputTokens +
      ' out',
  );
}

main().catch((err: unknown) => {
  console.error('Fatal:', err instanceof Error ? err.message : String(err));
  process.exit(1);
});
`;
}

function makeEnvExample(): string {
  return `# Nexus requires an Anthropic API key.
# Copy this file to .env and fill in your key.
# Never commit .env to version control.

ANTHROPIC_API_KEY=sk-ant-...
`;
}

function makeGitignore(): string {
  return `node_modules/
dist/
.env
*.js.map
`;
}

// ── Scaffold writer ───────────────────────────────

interface ScaffoldFile {
  relativePath: string;
  content: string;
}

function buildScaffold(projectName: string, targetDir: string): ScaffoldFile[] {
  void targetDir; // used externally
  return [
    { relativePath: 'package.json',    content: makePackageJson(projectName) },
    { relativePath: 'tsconfig.json',   content: makeTsConfig() },
    { relativePath: 'src/index.ts',    content: makeIndexTs(projectName) },
    { relativePath: '.env.example',    content: makeEnvExample() },
    { relativePath: '.gitignore',      content: makeGitignore() },
  ];
}

// ── Command builder ───────────────────────────────

export function buildInitCommand(): Command {
  return new Command('init')
    .description('Scaffold a new Nexus agent project')
    .argument('<name>', 'project name (used as directory name)')
    .option('--dir <path>', 'parent directory to create project in', '.')
    .action((name: string, opts: { dir: string }) => {
      const parentDir = resolve(opts.dir);
      const targetDir = join(parentDir, name);

      if (existsSync(targetDir)) {
        console.error(
          chalk.red('Error:') +
            ` Directory "${targetDir}" already exists. Choose a different name or --dir.`,
        );
        process.exit(1);
      }

      const spinner = ora(`Scaffolding project ${chalk.bold.hex('#6366f1')(name)}…`).start();

      try {
        // Create directory structure
        mkdirSync(join(targetDir, 'src'), { recursive: true });

        const files = buildScaffold(name, targetDir);

        for (const file of files) {
          writeFileSync(join(targetDir, file.relativePath), file.content, 'utf-8');
        }

        spinner.succeed(chalk.bold.hex('#10b981')('Project created!'));
      } catch (err: unknown) {
        spinner.fail('Failed to scaffold project');
        console.error(
          chalk.red('Error:'),
          err instanceof Error ? err.message : String(err),
        );
        process.exit(1);
      }

      console.log();
      console.log(
        chalk.dim('  Created: ') + chalk.white(targetDir),
      );
      console.log();
      console.log('  Files:');

      const files = [
        'package.json   — project manifest with nexus-core dependency',
        'tsconfig.json  — TypeScript config (strict, NodeNext)',
        'src/index.ts   — 2-agent team starter (Analyst → Critic)',
        '.env.example   — API key placeholder',
        '.gitignore     — ignores node_modules, dist, .env',
      ];

      for (const f of files) {
        console.log(chalk.dim('    ') + chalk.white(f));
      }

      console.log();
      console.log('  Next steps:');
      console.log(chalk.dim('    cd ') + chalk.bold(name));
      console.log(chalk.dim('    cp .env.example .env'));
      console.log(chalk.dim('    # Add your ANTHROPIC_API_KEY to .env'));
      console.log(chalk.dim('    npm install'));
      console.log(chalk.dim('    npm run dev "Your topic here"'));
      console.log();
    });
}
